[do not merge] Feature/pg 1236 email subscriptions
sleepio/community-app-web pull request #19
Opened 2021-03-17 20:46 UTC by wsbastian

**Reminder to create the PR against this repository, and not the base fork of `rafalp/Misago`.**

### JIRA Ticket

### Problem

### Solution

### Test Plan

#### Unit tests + Integration Tests

#### Manual Tests

### Rollout

#### Related PRs

2021-03-19 17:51 UTC, avi-bh submitted a review, later dismissed
Nice! I looked over the react code, but I'll let @jjosephbh review them since she'll know what she's looking at

2021-03-19 17:51 UTC, avi-bh commented on frontend/src/services/store.js
> +      window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
what is this for?

2021-03-19 18:00 UTC, wsbastian commented on frontend/src/services/store.js
> +      window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
It lets us hook redux devtools into our application state so we can visualize state structure.

2021-03-23 03:07 UTC, jjosephbh commented on frontend/src/components/threads/subscription.js
> +export class Disable extends React.Component {
Just a nit: Is this a button? The name does not really tell me what the component is really.

2021-03-23 07:06 UTC, jjosephbh requested changes

2021-03-23 07:06 UTC, jjosephbh commented on frontend/src/components/threads/subscription.js
> +export function update(props, newState, value) {
Trying to understand what this function is for. I am guessing you are updating the state with the changes? If so why don't you `setState` and then use tie that to the dispatch?

2021-03-23 13:25 UTC, wsbastian commented on frontend/src/components/threads/subscription.js
> +export class Disable extends React.Component {
Yeah, this was largely provisioned from the in-thread subscription example at https://github.com/sleepio/community-app-web/blob/f3d8b5a88f68621a284f47f6bdfcc65a6b6092bf/frontend/src/components/thread/subscription.js#L59-L59, and the naming came with.

2021-03-23 13:29 UTC, wsbastian commented on frontend/src/components/threads/subscription.js
> +export function update(props, newState, value) {
Also following the update model used by Misago from the and single-thread view at: 
https://github.com/sleepio/community-app-web/blob/f3d8b5a88f68621a284f47f6bdfcc65a6b6092bf/frontend/src/components/thread/subscription.js#L59-L59

Our change here was to modify what we're updating, and how we're updating them.

Being new to react, I don't entirely follow what the suggested approach would entail.

2021-03-23 15:41 UTC, jjosephbh commented on frontend/src/components/threads/subscription.js
> +export function update(props, newState, value) {
Hmm ok so you are following their code. OK I will let that go.

2021-03-23 15:42 UTC, jjosephbh commented on frontend/src/components/threads/subscription.js
> +export class Disable extends React.Component {
Sigh I swear. Ok.

2021-03-23 15:43 UTC, wsbastian commented on frontend/src/components/threads/subscription.js
> +export function update(props, newState, value) {
I'm interested to learn more about what you're preferred approach would be. If not within this PR than in a sidebar convo, if you've got the time.

2021-03-23 17:05 UTC, jjosephbh commented on frontend/src/components/threads/subscription.js
> +      // this feels redundant, but it's also what's being done in single thread.
It feels because it is lol

2021-03-23 17:05 UTC, jjosephbh submitted a review, later dismissed

2021-03-23 21:58 UTC, jjosephbh approved these changes

2021-03-29 19:59 UTC, merged