[PG-941] Core Framework Integration and Local Development Setup
sleepio/community-app-web pull request #2
Opened 2020-11-11 16:24 UTC by avi-bh

2020-11-12 20:50 UTC, avi-bh commented on frontend/gulpfile.js
> +var misago = '../webapp/src/misago/static/misago/';
only real change in this file

2020-11-13 07:44 UTC, vladdyk commented
Can you add the pull request template to the repo?

2020-11-13 07:52 UTC, vladdyk requested changes

2020-11-13 07:52 UTC, vladdyk commented on .gitignore
> -webapp/src/community_app/static/
why the remove

2020-11-13 07:52 UTC, vladdyk commented on README.md
> +1. Run `docker-compose up --build community_app_web`.
This should not be as separate step. It should be bhspin upped like everything else

2020-11-13 07:52 UTC, vladdyk commented on webapp/src/community_app/settings.py
> +    # TODO collectstatic config
what actually needs to be done for this TODO?

2020-11-13 07:52 UTC, vladdyk commented on webapp/src/big_health/services/community_app/service.py
> +class CommunityApp(BaseService):
It would be good to have the django apps publish a service so they can be integration tested but out of scope for this

2020-11-13 07:52 UTC, vladdyk commented on webapp/test/community_app/test_integration.py
> +@mock_service_call(ServiceCallMock("Blah", "1", "test", return_value="hello"))
I don't think this test is that useful. I think instead you could do

```python3
Factory.initialize("local")
assert Factory.create("CommunityApp", "1").loopback()
```

Then you'd actually be testing the plumbing

2020-11-13 16:12 UTC, avi-bh commented on .gitignore
> -webapp/src/community_app/static/
it was unnecessary. the static files go to the misago directory and are supposed to be kept in git

2020-11-13 16:13 UTC, avi-bh commented on README.md
> +1. Run `docker-compose up --build community_app_web`.
u right

2020-11-13 16:13 UTC, avi-bh commented on webapp/src/community_app/settings.py
> +    # TODO collectstatic config
its in the next ticket for Zappa integration. it needs staticfiles directories to collect

2020-11-13 16:14 UTC, avi-bh commented on webapp/src/big_health/services/community_app/service.py
> +class CommunityApp(BaseService):
agreed, that path is not straightforward though. would be nice to have for sure

2020-11-13 16:14 UTC, avi-bh commented on webapp/test/community_app/test_integration.py
> +@mock_service_call(ServiceCallMock("Blah", "1", "test", return_value="hello"))
u smaht

2020-11-13 16:46 UTC, vladdyk approved these changes
merci

2020-11-16 20:36 UTC, crfelizbh approved these changes
lgtm. Excellent work! We can even spin it up with bhspin!

2020-11-16 21:04 UTC, merged